from pathlib import Path
import re

root = Path('.')
app = root / 'ForexScalperApp'

(app / 'SecureCredentialStore.swift').write_text('''import Foundation\nimport Security\n\nstruct SecureCredentialStore {\n    static let shared = SecureCredentialStore()\n    private let service = "com.sirvimbi.ForexScalperApp.mt5"\n    private func key(_ name: String) -> String { "mt5.\\(name)" }\n\n    func read(_ name: String) -> String? {\n        let query: [String: Any] = [\n            kSecClass as String: kSecClassGenericPassword,\n            kSecAttrService as String: service,\n            kSecAttrAccount as String: key(name),\n            kSecReturnData as String: true,\n            kSecMatchLimit as String: kSecMatchLimitOne\n        ]\n        var item: CFTypeRef?\n        guard SecItemCopyMatching(query as CFDictionary, &item) == errSecSuccess, let data = item as? Data else { return nil }\n        return String(data: data, encoding: .utf8)\n    }\n\n    @discardableResult\n    func write(_ value: String, for name: String) -> Bool {\n        let query: [String: Any] = [\n            kSecClass as String: kSecClassGenericPassword,\n            kSecAttrService as String: service,\n            kSecAttrAccount as String: key(name)\n        ]\n        let data = Data(value.utf8)\n        let status = SecItemUpdate(query as CFDictionary, [kSecValueData as String: data] as CFDictionary)\n        if status == errSecItemNotFound {\n            var add = query\n            add[kSecValueData as String] = data\n            return SecItemAdd(add as CFDictionary, nil) == errSecSuccess\n        }\n        return status == errSecSuccess\n    }\n\n    @MainActor\n    func migrateLegacyUserDefaults() {\n        let defaults = UserDefaults.standard\n        for name in ["mt5AuthToken", "mt5Login", "mt5Password", "mt5Server"] {\n            if let legacy = defaults.string(forKey: name), !legacy.isEmpty {\n                if read(name) == nil { _ = write(legacy, for: name) }\n                defaults.removeObject(forKey: name)\n            }\n        }\n    }\n}\n''')

# DashboardViewModel
p = app / 'DashboardViewModel.swift'
s = p.read_text()
s = s.replace('@Published var maxConcurrentTrades: Int = 2 { didSet { syncRiskParameters() } }', '@Published var maxConcurrentTrades: Int = 2 { didSet { syncRiskParameters() } }\n    @Published var dailyTradeLimit: Int = 8')
for old, new in [
    ('@Published var mt5AuthToken: String = "al3RUuur7PCUjNiE1ja/Dzx5tpWz0EeqGUA618k6VY"', '@Published var mt5AuthToken: String = ""'),
    ('@Published var mt5Login: String = "134522550"', '@Published var mt5Login: String = ""'),
    ('@Published var mt5Password: String = "Kenya@254"', '@Published var mt5Password: String = ""'),
    ('@Published var mt5Server: String = "ExnessKE-MT5Trial9"', '@Published var mt5Server: String = ""')]:
    s = s.replace(old, new)
s = s.replace('loadSettings()\n        setupNotificationObservers()', 'loadSettings()\n        SecureCredentialStore.shared.migrateLegacyUserDefaults()\n        loadSecureMT5Credentials()\n        setupNotificationObservers()')
s = s.replace('''maxConcurrentTrades = UserDefaults.standard.integer(forKey: "maxConcurrentTrades") != 0 ?\n            UserDefaults.standard.integer(forKey: "maxConcurrentTrades") : 2''', '''maxConcurrentTrades = UserDefaults.standard.integer(forKey: "maxConcurrentTrades") != 0 ?\n            UserDefaults.standard.integer(forKey: "maxConcurrentTrades") : 2\n        dailyTradeLimit = UserDefaults.standard.integer(forKey: "dailyTradeLimit") != 0 ? UserDefaults.standard.integer(forKey: "dailyTradeLimit") : scalpingConfig.maxDailyTrades\n        scalpingConfig.maxDailyTrades = dailyTradeLimit''')
s = s.replace('''        mt5AuthToken = UserDefaults.standard.string(forKey: "mt5AuthToken") ?? "al3RUuur7PCUjNiE1ja/Dzx5tpWz0EeqGUA618k6VY"\n        mt5MagicNumber = UserDefaults.standard.integer(forKey: "mt5MagicNumber") != 0 ?\n            UserDefaults.standard.integer(forKey: "mt5MagicNumber") : 888888\n        mt5Login = UserDefaults.standard.string(forKey: "mt5Login") ?? "134522550"\n        mt5Password = UserDefaults.standard.string(forKey: "mt5Password") ?? "Kenya@254"\n        mt5Server = UserDefaults.standard.string(forKey: "mt5Server") ?? "ExnessKE-MT5Trial9"''', '''        mt5MagicNumber = UserDefaults.standard.integer(forKey: "mt5MagicNumber") != 0 ?\n            UserDefaults.standard.integer(forKey: "mt5MagicNumber") : 888888\n        loadSecureMT5Credentials()''')
s = s.replace('UserDefaults.standard.set(maxConcurrentTrades, forKey: "maxConcurrentTrades")', 'UserDefaults.standard.set(maxConcurrentTrades, forKey: "maxConcurrentTrades")\n        UserDefaults.standard.set(dailyTradeLimit, forKey: "dailyTradeLimit")\n        scalpingConfig.maxDailyTrades = dailyTradeLimit')
s = s.replace('''        UserDefaults.standard.set(mt5AuthToken, forKey: "mt5AuthToken")\n        UserDefaults.standard.set(mt5MagicNumber, forKey: "mt5MagicNumber")\n        UserDefaults.standard.set(mt5Login, forKey: "mt5Login")\n        UserDefaults.standard.set(mt5Password, forKey: "mt5Password")\n        UserDefaults.standard.set(mt5Server, forKey: "mt5Server")''', '''        UserDefaults.standard.set(mt5MagicNumber, forKey: "mt5MagicNumber")\n        _ = SecureCredentialStore.shared.write(mt5AuthToken, for: "mt5AuthToken")\n        _ = SecureCredentialStore.shared.write(mt5Login, for: "mt5Login")\n        _ = SecureCredentialStore.shared.write(mt5Password, for: "mt5Password")\n        _ = SecureCredentialStore.shared.write(mt5Server, for: "mt5Server")\n        UserDefaults.standard.removeObject(forKey: "mt5AuthToken")\n        UserDefaults.standard.removeObject(forKey: "mt5Login")\n        UserDefaults.standard.removeObject(forKey: "mt5Password")\n        UserDefaults.standard.removeObject(forKey: "mt5Server")''')
methods = '''    private func loadSecureMT5Credentials() {\n        mt5AuthToken = SecureCredentialStore.shared.read("mt5AuthToken") ?? ""\n        mt5Login = SecureCredentialStore.shared.read("mt5Login") ?? ""\n        mt5Password = SecureCredentialStore.shared.read("mt5Password") ?? ""\n        mt5Server = SecureCredentialStore.shared.read("mt5Server") ?? ""\n    }\n\n    func disconnectFromMT5() async {\n        isConnecting = true\n        godLog("🔌 MT5: Disconnect requested", level: .info)\n        await MT5Service.shared.disconnect()\n        mt5Connected = false\n        isConnecting = false\n        godLog("🔌 MT5: Disconnected", level: .success)\n    }\n\n'''
s = s.replace('    func connectToIG() {', methods + '    func connectToIG() {') if 'func disconnectFromMT5' not in s else s
s = s.replace('''        refreshTimer = Timer.publish(every: interval, on: .main, in: .common)\n            .autoconnect()\n            .sink { [weak self] _ in\n                self?.refreshData()\n            }''', '''        refreshTimer = Timer.publish(every: interval, on: .main, in: .common)\n            .autoconnect()\n            .sink { [weak self] _ in\n                Task { @MainActor in\n                    await self?.refreshAccountInfo()\n                    self?.refreshData()\n                }\n            }''')
p.write_text(s)

# Coordinator security + guaranteed signal dismissal.
p = app / 'RefactoredAppCoordinator.swift'; s = p.read_text()
s = s.replace('''let mt5Login = UserDefaults.standard.string(forKey: "mt5Login") ?? "436886946"\n        let mt5Password = UserDefaults.standard.string(forKey: "mt5Password") ?? "Kenya@254"\n        let mt5Server = UserDefaults.standard.string(forKey: "mt5Server") ?? "ExnessKE-MT5Trial9"''', '''let mt5Login = SecureCredentialStore.shared.read("mt5Login") ?? ""\n        let mt5Password = SecureCredentialStore.shared.read("mt5Password") ?? ""\n        let mt5Server = SecureCredentialStore.shared.read("mt5Server") ?? ""''')
if 'func denySignal(_ signal: Signal)' not in s:
    s = s.replace('    func acceptSignal(_ signal: Signal) {', '''    func denySignal(_ signal: Signal) {\n        signals.removeAll { $0.id == signal.id }\n        godLog("🚫 Signal denied and dismissed | \\(signal.symbol)", level: .info)\n        objectWillChange.send()\n    }\n\n    func acceptSignal(_ signal: Signal) {''')
s = s.replace('''            await tradeHistory.addTrade(trade)\n\n            godLog("✅ Trade opened: \\(normalizedSymbol) - Risk: KES \\(String(format: "%.2f", positionSize.riskAmount))", level: .success)''', '''            await tradeHistory.addTrade(trade)\n\n            await MainActor.run {\n                self.signals.removeAll { $0.id == normalizedSignal.id }\n                self.objectWillChange.send()\n            }\n\n            godLog("✅ Trade opened: \\(normalizedSymbol) - Risk: KES \\(String(format: "%.2f", positionSize.riskAmount))", level: .success)''')
p.write_text(s)

# MT5 service security + disconnect state reset.
p = app / 'MT5Service.swift'; s = p.read_text()
s = s.replace('let saved = UserDefaults.standard.string(forKey: "mt5AuthToken") ?? "al3RUuur7PCUjNiE1ja/Dzx5tpWz0EeqGUA618k6VY"', 'let saved = SecureCredentialStore.shared.read("mt5AuthToken") ?? ""')
if 'func disconnect()' not in s:
    s = s.replace('    func initialize(login: Int, password: String, server: String) async throws {', '''    func disconnect() {\n        _isConnected = false\n        lastWorkingPath = nil\n        godLog("🔌 MT5Service: connection state cleared", level: .diagnostic)\n    }\n\n    func initialize(login: Int, password: String, server: String) async throws {''')
p.write_text(s)

# Settings: daily limit and non-overlapping disconnect button.
p = app / 'SettingsView.swift'; s = p.read_text()
anchor = '''                                    settingsRow("Max Concurrent Trades") {\n                                        HStack(spacing: 12) {\n                                            Text("\\(viewModel.maxConcurrentTrades)")\n                                                .font(.system(size: 12, weight: .bold, design: .monospaced))\n                                                .foregroundColor(.accentCyan)\n                                                .frame(width: 30, alignment: .trailing)\n                                            Stepper("", value: $viewModel.maxConcurrentTrades, in: 1...10)\n                                                .labelsHidden()\n                                        }\n                                    }'''
if 'settingsRow("Daily Trade Limit")' not in s:
    s = s.replace(anchor, anchor + '''\n\n                                    settingsRow("Daily Trade Limit") {\n                                        HStack(spacing: 12) {\n                                            Text("\\(viewModel.dailyTradeLimit)")\n                                                .font(.system(size: 12, weight: .bold, design: .monospaced))\n                                                .foregroundColor(.accentGold)\n                                                .frame(width: 30, alignment: .trailing)\n                                            Stepper("", value: $viewModel.dailyTradeLimit, in: 1...100).labelsHidden()\n                                        }\n                                    }''')
s = s.replace('ScalpingConfig.shared.enableHourlyLimit = viewModel.enableHourlyLimit', 'ScalpingConfig.shared.enableHourlyLimit = viewModel.enableHourlyLimit\n        ScalpingConfig.shared.maxDailyTrades = viewModel.dailyTradeLimit')
old = '''                                    HStack(spacing: 10) {\n                                        Button(action: {\n                                            Task {\n                                                await viewModel.connectToMT5()\n                                            }\n                                        }) {'''
if 'Text("DISCONNECT")' not in s:
    start = s.find(old)
    if start < 0: raise SystemExit('MT5 button anchor not found')
    end = s.find('                                    }\n                                }\n                                .padding(16)\n                            }', start)
    if end < 0: raise SystemExit('MT5 button closing anchor not found')
    replacement = '''                                    HStack(spacing: 10) {\n                                        Button(action: { Task { await viewModel.connectToMT5() } }) {\n                                            HStack(spacing: 6) { Image(systemName: "bolt.fill"); Text(viewModel.mt5Connected ? "RECHECK MT5" : "CONNECT MT5") }\n                                                .font(.system(size: 11, weight: .bold, design: .monospaced))\n                                                .frame(maxWidth: .infinity).padding(.vertical, 10)\n                                                .background(Color.accentCyan).foregroundColor(.bgPrimary).cornerRadius(7)\n                                        }.buttonStyle(.plain).disabled(viewModel.isConnecting)\n                                        Button(action: { Task { await viewModel.disconnectFromMT5() } }) {\n                                            HStack(spacing: 6) { Image(systemName: "bolt.slash.fill"); Text("DISCONNECT") }\n                                                .font(.system(size: 11, weight: .bold, design: .monospaced))\n                                                .frame(maxWidth: .infinity).padding(.vertical, 10)\n                                                .background(viewModel.mt5Connected ? Color.accentRed.opacity(0.18) : Color.bgSecondary)\n                                                .foregroundColor(viewModel.mt5Connected ? .accentRed : .textMuted).cornerRadius(7)\n                                        }.buttonStyle(.plain).disabled(viewModel.isConnecting || !viewModel.mt5Connected)\n                                    }\n'''
    s = s[:start] + replacement + s[end:]
p.write_text(s)

# Security assertion.
for name in ['DashboardViewModel.swift','RefactoredAppCoordinator.swift','MT5Service.swift']:
    text = (app / name).read_text()
    for secret in ['Kenya@254','al3RUuur7PCUjNiE1ja/Dzx5tpWz0EeqGUA618k6VY','"134522550"','"ExnessKE-MT5Trial9"']:
        if secret in text: raise SystemExit(f'{secret} remains in {name}')

# Remove patch workflow/script after this one-time transformation.
for path in [root/'.github/workflows/apply-agent-trade-fixes.yml', root/'.github/workflows/apply-agent-fixes-2.yml', root/'.github/patch_agent_fixes.py']:
    if path.exists(): path.unlink()
print('agent patch completed')
